kind: Pod
apiVersion: v1
metadata:
  name: busybox
  labels:
    name: busybox  
spec:
  containers:
    - name: busybox
      image: registry_url/busybox
      imagePullPolicy: IfNotPresent
      command:
      - sleep
      - "360000"