kind: Pod
apiVersion: v1
metadata:
  name: curl
  labels:
    name: curl  
spec:
  containers:
    - name: curl
      image: registry_url/curl
      imagePullPolicy: IfNotPresent
      command:
      - sleep
      - "360000"