# Configuration to deploy release version of the heapster.
#
# Example usage: kubectl create -f <this_file>
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: heapster
  namespace: kube-system
  labels:
    app: heapster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heapster
      version: v1.1.0
  template:
    metadata:
      labels:
        app: heapster
        version: v1.1.0
    spec:
      containers:
      - name: heapster      
        image: registry_url/heapster:v1.1.0
        imagePullPolicy: IfNotPresent
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/ssl/certs
          readOnly: true
      volumes:
      - name: ssl-certs
        hostPath:
          path: /ssl            
---
kind: Service
apiVersion: v1
metadata:
  name: heapster
  namespace: kube-system
  labels:
    app: heapster
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: heapster